### ISSUE TITLE
AES for windows

### ISSUE THREAD

**Issue by hardkano** [WyvernTKC/cpuminer-gr-avx2#1]
Could you add AES for windows ? don't see it in the hotfix. I have a cpu that use only that.

**Comment by t32768** [comment]
I'm joining this request... I have about 20 cpus that have SSE2/AES but not AVX2, mostly 7th gen Pentiums.... recent rplant miner already supports them, but has other issues on other pools than rplant. Would love to switch back to your miner, thanks!!!

**Comment by michal-zurkowski** [comment]
non-AES support is going to be added in the next release.

**Comment by hardkano** [comment]
Thanks for the new released !
