### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by gasien** [WyvernTKC/cpuminer-gr-avx2#10]
Windows 10 Defender live service memory usage is going up until system crashes (cpuminer-avx2.exe).

**Comment by michal-zurkowski** [comment]
Unfortunately, that is Windows Defender "issue". I would recommend making an exception for the miner.
Other users also noticed the same issue if the miner starts pretty close to the boot, like autostart script or just after you start the system. Running it after some time after boot where Windows Defender caches up was enough for them to solve the issue.
