### ISSUE TITLE
wrong thread usage

### ISSUE THREAD

**Issue by GuilhermeLessa** [WyvernTKC/cpuminer-gr-avx2#100]
My CPU is a Ryzen 7 5700g with 16 threads.

When i configure json with 16, or fix 0 zero, my CPU usage oscile between 70 and sometimes 100%;

When i overload threads json configuration, like 24 or 32, so cpu usage aways do 100%.

Theres somethink wrong with this threads manager.

**Images**
16 THREADS 70% USAGE:
https://drive.google.com/file/d/1Szj5jQZ0ehAt5x1_yJm8-CvXAMHpE42K/view?usp=sharing

24 THREADS FULL CPU USED
https://drive.google.com/file/d/1GJ4fULO0Yefa1pYG-Vvmq5-do8OWd9ch/view?usp=sharing

**Comment by michal-zurkowski** [comment]
Did you benchmark it to get those hashrates? Either benchmark (or run the miner for at least 24h which is not only comparable but good enough).
Include benchmark results.

Miner is doing its job properly. It is getting you the most amount of hashrate there is. APUs from AMD has cut down cache size which means they need to have some threads disabled on some of the heavier rotations. In those cases, fewer threads = more hash rate. This is mostly done on Intels, Zen/Zen+ and AMD APUs (this is what you have).
When you increase the number of threads you are overloading the CPU making it perform much worse.
