### ISSUE TITLE
A bug due to missing unlocking

### ISSUE THREAD

**Issue by ryancaicse** [WyvernTKC/cpuminer-gr-avx2#101]
It seems the lock release of **stats_lock** is missing before **Line 4857**. Should it be a bug?

https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/d2e391d29a0e9a42de2b85c25d51824b58554411/cpu-miner.c#L4841-L4857

**Comment by michal-zurkowski** [comment]
It is released here: https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/d2e391d29a0e9a42de2b85c25d51824b58554411/cpu-miner.c#L4867

**Comment by ryancaicse** [comment]
**Line 4857** has a return so the function returns with the lock acquired.

**Comment by michal-zurkowski** [comment]
return from `main` will close the program entirely. It means it was not able to create threads properly so it does not matter.

**Comment by ryancaicse** [comment]
OK, thanks for your comments. But it does not harm to releasing locks for code symmetry.
