### ISSUE TITLE
Not using all threads?

### ISSUE THREAD

**Issue by zenon8888** [WyvernTKC/cpuminer-gr-avx2#103]
Hi, i switched the monitor on, and i saw that one of the treads (the first one marked with arrow was not active, saw this couple of times, but i wonder why. Could it be that i have not defined Affinity and it spiked on the other two threads?(the last two, im using only 10/12 as I saw the best results with this in the long run)
![CPU](https://user-images.githubusercontent.com/94313181/142260923-cc7fc502-6b1e-4d8f-92f6-42f40e7f8338.jpg)

**Comment by michal-zurkowski** [comment]
Same question as #100 
Miner automatically disables threads if it is beneficial to the hashrate. You disabling 2 threads manually lose like 15% of normal performance from just that.

**Comment by zenon8888** [comment]
Aha :) i have to test it more, as i'm also mining with my GPU switched on hardware scheduler, and saw lower ETH with 12/12 and lower GR
