### ISSUE TITLE
winring0x64.sys remove after use

### ISSUE THREAD

**Issue by mchernikovv** [WyvernTKC/cpuminer-gr-avx2#106]
I can not delete the folder with the miner because of the file winring0x64.sys.  It is obtained only after a reboot. Please tell me how to complete all processes to delete without rebooting.

**Comment by michal-zurkowski** [comment]
Are you using the latest version of the miner? 1.2.4.1?
I have no problem deleting the file after using the miner and closing it.

**Comment by mchernikovv** [comment]
Yes, the latest version. It deletes only from every second machine without problems.
