### ISSUE TITLE
Is there a centos version?

### ISSUE THREAD

**Issue by liuyueyun6** [WyvernTKC/cpuminer-gr-avx2#11]
Is there a centos version?

**Comment by michal-zurkowski** [comment]
There are no precompiled binaries for CentOS but you can compile them from the source just fine.
1. Install required libs: `sudo yum install automake libcurl-devel openssl-devel jansson-devel gmp-devel zlib-devel numactl-devel  make  gcc gcc-c++ kernel-devel`
2. Clone the repo: `git clone https://github.com/WyvernTKC/cpuminer-gr-avx2 cpuminer-gr && cd cpuminer-gr`
3. Build the binaries: `./build.sh`
4. You should have a proper binaries in the current folder as `cpuminer`
