### ISSUE TITLE
Miner doesn't stop after terminal window close [Ubuntu 20.04]

### ISSUE THREAD

**Issue by nzkozar** [WyvernTKC/cpuminer-gr-avx2#114]
I'm looking for a way to stop mining.
Simply closing the terminal window doesn't do the job as the CPU load remains at 100% and also starting a new cpu miner instance will fail.
Ctrl+C, Ctrl+D doesn't have any effect.
I was also unable to identify any process associated with the CPU load, to shut that down.

So how can I safely shut down the miner, without restarting the machine? (I couldn't find anything on this in the documentation)

**Comment by nzkozar** [comment]
[FIXED] Ctrl+C works, just had to disable my terminal shortcuts

**Comment by michal-zurkowski** [comment]
Normal Ctrl+C should work without any issues unless you did some changes to the terminal or run it in the background. In those cases killing the process directly would probably be the best option.
You can do it with `sudo pkill cpuminer`
