### ISSUE TITLE
Why does my graphics card perform better than my CPU?

### ISSUE THREAD

**Issue by sebakine** [WyvernTKC/cpuminer-gr-avx2#115]
Hello everyone, I hope you have a good weekend.
I don't know what is happening but the performance of my CPU is lower than that of my GPU. Anyone have any explanation for this?
My CPU is a RYZEN 7 4800H 8C 16T, while my GPU is a 5600XT. The Ryzen gives me a power of 600h / s and the 5600 gives me 1.2kh / s.
Please someone who can guide, I will be eternally grateful.
I am in FlockPool US tuned config.
Thank you so much people...

**Comment by zenon8888** [comment]
It looks like the CPU is underperforming, but what are you configuration settings? Any OC on the CPU? PBO or all core?(its more advised to use manual all core OC than PBO) Have you run tune with all other things closed? All the background processes closed? Did you check system stability with Prime95 or LinpackXtreme if you OC? Maybe the temps are thermal throttling the CPU?

**Comment by michal-zurkowski** [comment]
It is a mobile chip with just 0.5 MiB of L3 cache per thread. It is understandable that it will perform "bad".

**Comment by zenon8888** [comment]
8mb of L3 cache to be precise, but yeah still as low as Intel, my bad didn't check the specs :) 
https://www.amd.com/en/products/apu/amd-ryzen-7-4800h
