### ISSUE TITLE
Could not prepare Huge Pages

### ISSUE THREAD

**Issue by QiangWei-Wade** [WyvernTKC/cpuminer-gr-avx2#124]
Hello,

I encounter the following warnings on a AMD Ryzen 3600+B450 with Windows 10. Am I supposed to reboot the computer? Please advise.

[2021-11-22 10:09:49] Huge pages support was successfully enabled, but reboot is required to use it
[2021-11-22 10:09:49] Could not prepare Huge Pages.

**Comment by michal-zurkowski** [comment]
Everything is explained in your issue description, you need to reboot the PC:
`[2021-11-22 10:09:49] Huge pages support was successfully enabled, but reboot is required to use it`
