### ISSUE TITLE
Configuring cores

### ISSUE THREAD

**Issue by josifoski** [WyvernTKC/cpuminer-gr-avx2#126]
I've found this here https://github.com/JayDDee/cpuminer-opt/wiki/CLI-and-config-options
-c, --config=FILE load a JSON-format configuration file

But I didn't find anywhere format of config file (so far)

**Comment by josifoski** [comment]
I simply want to set one core only (I have 2), for heating reasons, also for availability of PC

**Comment by michal-zurkowski** [comment]
The format is like said in the description, JSON.
You can also see it in the example config.json and in readme how to add new things.
the long flag is `--benchmark`, then in JSON it will be `"benchmark": true`

If you want to use just 1 thread, in the example config there is already `"threads": 0,` just set it to `1`
