### ISSUE TITLE
[Feature Request] Auto reload config

### ISSUE THREAD

**Issue by Vin-Ren** [WyvernTKC/cpuminer-gr-avx2#129]
I often change the configuration in the morning to limit the miner usage and make my old pc run a bit smoother. Every time I changed the configuration, I need to restart the mining and it often shows something like: `Using malloc for allocation method consider restarting your pc` I don't know whether it affects the miner performance or not, but to be safe I restarted it. After a while, it started becoming more annoying. 

If the memory allocation problem is an issue from starting the binary as a whole, a solution I could think of is auto reloading the configuration. This feature would become handy for people who frequently edit the config file.

**Comment by michal-zurkowski** [comment]
Reloading would be problematic as many aspects of the miner depend on it.
The fragmented memory (malloc thing) is only because Windows is not so good at managing its memory.

**Comment by Vin-Ren** [comment]
> Reloading would be problematic as many aspects of the miner depend on it. The fragmented memory (malloc thing) is only because Windows is not so good at managing its memory.

That's unknown to me prior to this, any other way to solve it than restarting?

**Comment by michal-zurkowski** [comment]
Maybe there are some tools. Im unaware of those as Windows is not my primary OS.
Using malloc instead of proper Large Pages will definitely reduce performance.

**Comment by Vin-Ren** [comment]
That's unfortunate, thanks though. Should I close the issue?
