### ISSUE TITLE
Several Huge page errors at second launch - Solved

### ISSUE THREAD

**Issue by Chewyb00gie** [WyvernTKC/cpuminer-gr-avx2#131]
just started the miner, not sure if the configuration/detection was done correctly but I did let it run until the end.

Screenshot of the issue : 
![image](https://user-images.githubusercontent.com/94975793/143253628-28a4f05c-d423-495f-89c8-a1e295212e21.png)

**Comment by Chewyb00gie** [comment]
Thought running as administrator would fix the issue, this is what I am seeing now : ![image](https://user-images.githubusercontent.com/94975793/143253957-fde69cb2-f4fa-43ca-bf88-3b6edebeac85.png)

**Comment by Chewyb00gie** [comment]
Restarting and running as administrator now solved the issue : 
![image](https://user-images.githubusercontent.com/94975793/143255673-b373391d-556a-47f6-a4ae-a13f66799e67.png)

**Comment by michal-zurkowski** [comment]
Yes, on Windows you have to run as admin, restart PC and then run again
