### ISSUE TITLE
mining low

### ISSUE THREAD

**Issue by mtmtmt123** [WyvernTKC/cpuminer-gr-avx2#153]
hello in cpu tune full it found over 1500hs but if tune full complete4 and start mining i have only 700
and by another pc found over 1000 and mine only 150hs

what is the problem?
Thanks

**Comment by michal-zurkowski** [comment]
GR consists of many algorithms. This 1500 is not something you will see all the time. You can run a benchmark to see your hashrate on each rotation and your expected average from the PC.

**Comment by mtmtmt123** [comment]
Thanks
