### ISSUE TITLE
problem - make 

### ISSUE THREAD

**Issue by mushko77** [WyvernTKC/cpuminer-gr-avx2#158]
Hi I try to install and run on debian. After I try to do make this comes as a problem:

/usr/bin/ld: cpuminer-virtual_memory.o: in function `InitHugePages':
virtual_memory.c:(.text+0x1c): undefined reference to `numa_max_node'
/usr/bin/ld: virtual_memory.c:(.text+0x2b): undefined reference to `numa_num_possible_cpus'
/usr/bin/ld: virtual_memory.c:(.text+0x73): undefined reference to `numa_allocate_cpumask'
/usr/bin/ld: virtual_memory.c:(.text+0x81): undefined reference to `numa_node_to_cpus'
/usr/bin/ld: virtual_memory.c:(.text+0x9a): undefined reference to `numa_bitmask_isbitset'
/usr/bin/ld: virtual_memory.c:(.text+0xb5): undefined reference to `numa_bitmask_free'
/usr/bin/ld: algo/gr/cpuminer-gr.o: in function `gr_hash':
/root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:170: undefined reference to `sph_shavite512_sw_init'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:170: undefined reference to `sph_shavite512_sw'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:170: undefined reference to `sph_shavite512_sw_close'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:171: undefined reference to `sph_shavite512_sw_init'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:171: undefined reference to `sph_shavite512_sw'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:171: undefined reference to `sph_shavite512_sw_close'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:84: undefined reference to `sph_shavite512_sw_init'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:84: undefined reference to `sph_shavite512_sw'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:84: undefined reference to `sph_shavite512_sw_close'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:85: undefined reference to `sph_shavite512_sw_init'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:85: undefined reference to `sph_shavite512_sw'
/usr/bin/ld: /root/git/cpuminer-gr-avx2/algo/gr/gr.cpp:85: undefined reference to `sph_shavite512_sw_close'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:981: cpuminer] Error 1
make[2]: Leaving directory '/root/git/cpuminer-gr-avx2'
make[1]: *** [Makefile:2076: all-recursive] Error 1
make[1]: Leaving directory '/root/git/cpuminer-gr-avx2'
make: *** [Makefile:616: all] Error 2

Before this i had to solve some problems witch i did.

In file included from ./algo-gate-api.h:4,
                 from algo/sha/sha256d.h:1,
                 from cpu-miner.c:27:
./miner.h:42:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.

cpuminer-virtual_memory.o `test -f 'virtual_memory.c' || echo './'`virtual_memory.c
virtual_memory.c:191:10: fatal error: numa.h: No such file or directory
 #include <numa.h> // numa_max_node
compilation terminated.

to solve these i used:
apt-get install libcurl-dev
apt-get install libnuma-dev

please help
Thanks 
Adam

**Comment by michal-zurkowski** [comment]
Looks like you did not follow the linux install instructions

**Comment by mushko77** [comment]
> Looks like you did not follow the linux install instructions

I did follow this:
https://docs.raptoreum.com/#/howtomine 

but i'm not on ubuntu but debian 10.11

**Comment by michal-zurkowski** [comment]
https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/main/INSTALL_LINUX

You can look at ubuntu as debian as it is based on it

**Comment by mushko77** [comment]
after first apt-get install i get

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libcurl4-openssl-dev : Depends: libcurl4 (= 7.64.0-4+deb10u2) but 7.74.0-1.2~bpo10+1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by michal-zurkowski** [comment]
You can try without this one or just fix the broken package to match what it needs.

**Comment by mushko77** [comment]
I tried but it failed

**Comment by michal-zurkowski** [comment]
`sudo apt update`
`sudo apt install build-essential automake libssl-dev libjansson-dev libgmp-dev zlib1g-dev libnuma-dev git`
`./build.sh`

**Comment by mushko77** [comment]
It works now. Thank you so much for your time.
