### ISSUE TITLE
Rocket lake

### ISSUE THREAD

**Issue by bonifacio123** [WyvernTKC/cpuminer-gr-avx2#17]
Is the cpuminer-avx512-sha version compiled with -march rocket lake? Thought I'd ask before trying to compile myself under Ubuntu 20.04 since Jay D says his file is not. I believe gcc 11 supports this platform. What would be your recommendation -march rocketlake or -march -rocketlake -march sha? The docs says to use -march native but am not sure if native is specific enough. Thank you.

**Comment by michal-zurkowski** [comment]
If you compile it for yourself and will use it on the machine, compiling as -march=native is gonna provide the best possible matching there is.
Here you can see what we use for each individual instruction set: https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/main/build-allarch.sh It is for now compiled as `-march=cascadelake` with `-msha` and `-mtune=intel`. That is what we are using as gcc-10 is for now preferred compiler version.

**Comment by bonifacio123** [comment]
Perfect! Thank you for taking the time to response.
