### ISSUE TITLE
FATAL ERROR <x86intrin.h>

### ISSUE THREAD

**Issue by garzeth** [WyvernTKC/cpuminer-gr-avx2#170]
why I get this error when I use git repository on my termux terminal Ubuntu 20.04 I did all steps correctly but I always get this error

**Comment by michal-zurkowski** [comment]
Can you provide more context about the errors?
What is the machine you are trying to compile it on?
Remember that this repository will only compile on AMD64 architectures (x86_64 for intel naming)

**Comment by garzeth** [comment]
Oppo a5s
arm cortex cpus

**Comment by garzeth** [comment]
so actually i had a cpuminer gr installed two days ago and did some mining but i accidently deleted the data in termux causing the miner to be deletd aswell oh by the way i think it was a fork of the wyvern cpuminer -gr i installed on my termux ubuntu 20.04

**Comment by garzeth** [comment]
so right now i want to try this miner i did all the steps correctly like the gits but when i put the ./build.sh command it was running good but suddenly it showed a fatal error so ithink thats all even using the other configuring commands didny help and my phone is on the 64 architecture

**Comment by michal-zurkowski** [comment]
This version is not compatible with arm.
For arm compatible cpuminer try this: https://github.com/michal-zurkowski/cpuminer-gr
There is also tutorial for termux for phones here: https://github.com/GL513/cpuminer-in-termux/

Xmrig is also available for arm cpus

**Comment by garzeth** [comment]
thanks I kinda forgot that your fork of the miner was the one I used two days ago so anyway thanks for the help
