### ISSUE TITLE
Illegal Instruction (core dumped) Threadripper PRO 3975WS 32-core

### ISSUE THREAD

**Issue by wakinglf** [WyvernTKC/cpuminer-gr-avx2#21]
Core took a dump while running --tune-full

> CPU: AMD Ryzen Threadripper PRO 3975WX 32-Cores
> SW built on Jul 29 2021 with GCC 10.3.0
> CPU features:  AVX2    AES SHA
> SW features:   AVX2   VAES SHA
> Algo features: AVX2   VAES
> 
> Starting miner with AVX2 AES...
> 
> [2021-09-28 16:18:42] CPU affinity [!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!]
> [2021-09-28 16:18:42] Could not load 'tune_config' file
> [2021-09-28 16:18:42] Could not find/load 'tune_config' file. Miner will perform tuning operation.
> [2021-09-28 16:18:42] Default tuning process takes 80 minutes to finish.
> [2021-09-28 16:18:42] --tune-simple takes 54 minutes.
> [2021-09-28 16:18:42] --tune-full takes 115 minutes.
> [2021-09-28 16:18:42] Starting --tune-full tuning (115 minutes)
> [2021-09-28 16:18:42] Add --no-tune to your commandline to disable it.
> [2021-09-28 16:18:42] Huge Pages set up successfully.
> [2021-09-28 16:18:42] MSR Ryzen v1
> [2021-09-28 16:18:42] Arch Zen2
> [2021-09-28 16:18:42] MSR set up successfully.
> [2021-09-28 16:18:42] Stratum connect ghostrider.na.mine.zergpool.com:5354
> [2021-09-28 16:18:43] 62 of 64 miner threads started using 'gr' algorithm
> [2021-09-28 16:18:44] Testing rotation: 01 (0 0 X X 0 X) -> Dark + Darklite + Fast
> [2021-09-28 16:18:44] Testing: Dark (1way) + Darklite (1way) + Fast (1way)
> Illegal instruction (core dumped)

This tune is working great on my 5950X running in Windows 10, however, not so hot on the Ubuntu 20.04.2 LTS.

**Comment by michal-zurkowski** [comment]
Hello,
You are trying to run zen3 variant pf the binaries on this threadripper which is zen2. Try running the miner with this variant instead.

**Comment by wakinglf** [comment]
Oh thank you so much!  Let me try zen2.


Le Wang CFO

901-463-0136

***@***.******@***.***>



Kahkoon Technologies

Chicago ● Los Angeles ● San Diego

________________________________

**Comment by wakinglf** [comment]
RESOLVED!
