### ISSUE TITLE
1.1.9 Has been testing condition

### ISSUE THREAD

**Issue by SNThao** [WyvernTKC/cpuminer-gr-avx2#27]
Developers to hello，Windows 10 64，Running but has been in a test network

**Comment by WyvernTKC** [comment]
你能提交错误的输出吗？我们需要这个来理解。

**Comment by michal-zurkowski** [comment]
More like THEY have a bug that does not count skipped (not validated) shares so users are not getting paid properly for the work they did/submitted.
Until rplant fixes their thing, you will either have to use 1.1.9 or switch pools.

**Comment by xxSSSxx-1978** [comment]
Hello, 1.1.9 Ubuntu, 32x64 processor, all threads do not work, and why does the check pass after each new start, there is no --tune in the file. [http://prntscr.com/1wt0vyl](url)
