### ISSUE TITLE
Affinity incorrectly set on > 63 thread CPUs

### ISSUE THREAD

**Issue by Chipcraft** [WyvernTKC/cpuminer-gr-avx2#41]
The issue is back in 1.2.1, 1.2.0 was fine in this regard.

_Originally posted by @Chipcraft in https://github.com/WyvernTKC/cpuminer-gr-avx2/issues/18#issuecomment-940444342_

Giving no "--threads" or "cpu-affinity" parameters results in only the first 32 logical cores being used (i.e. 16C/32T). Adding "--threads 63 --cpu-affinity 0x7FFFFFFFFFFFFFFF" as a parameter works, leaving only one of the logical (SMT thread) unutilized.

Windows 10 Pro.

**Comment by michal-zurkowski** [comment]
Thanks for reporting. Do you mind contacting me on Discord `Delgon (Naen)#1859` ?
