### ISSUE TITLE
Software does not match CPU features problem

### ISSUE THREAD

**Issue by jude2world** [WyvernTKC/cpuminer-gr-avx2#65]
Hi, I'm new to Raptoreum mining. I use version 1.2.3 and get very low hashrate. I think it's because of the problems I've given you. Is there anything I can do?

I am a Windows 11 insider user and my processor is the Ryzen 5 3600.
My English not good. I'm sorry.
![rtm1](https://user-images.githubusercontent.com/93853730/140633352-bd78d1fe-ec75-4abe-8633-7901c19ecf17.png)
![rtm2](https://user-images.githubusercontent.com/93853730/140633356-6628a987-410a-430f-83ff-2dca7a2c1e54.png)

**Comment by michal-zurkowski** [comment]
Yes, that will be addressed in the next release.
For now open cpuminer.bat and in change line 11 from `set INST_OVERRIDE=` to `set INST_OVERRIDE=zen2`

**Comment by jude2world** [comment]
> Yes, that will be addressed in the next release. For now open cpuminer.bat and change line 11 from `set INST_OVERRIDE=` to `set INST_OVERRIDE=zen2` The overall problem is because of the Windows 11, and insider version on top of that where they deleted `wmic` that was used to get info about the CPU. If you tuned the miner with the setup you currently have, I highly recommend deleting `tune_config` file and retuning with proper binaries.

Hi, I'm sorry for my late response to the time difference. I don't know how, but I made things worse. :D 

I removed the app and downloaded it again. I changed line 11, like you said. I'm getting a different error right now. At first I thought I'd got it because I changed line 11, and I restored it, but nothing changed. 
![hata](https://user-images.githubusercontent.com/93853730/140667780-d5e52883-095c-4212-93f0-c65ca6e52454.png)

**Comment by michal-zurkowski** [comment]
I told you to set it as 
`set INST_OVERRIDE=zen2`
not
`set INST_OVERRIDE="to"`
