### ISSUE TITLE
Windows version packaging error

### ISSUE THREAD

**Issue by vanthoi** [WyvernTKC/cpuminer-gr-avx2#70]
Package mingw64 crashes on Windows and Ubuntu versions with MinGW64.
Error is output when building scripted:
`./configure CFLAGS="-march=znver1 -Wall" --with-crypto --with-curl --host=x86_64-w64-mingw32` (success, no errors)
make -j 8 :
`./simd-utils/simd-128.h: Print function 'mm128_mask_32':
./simd-utils/simd-128.h:167:22: error: the last argument must be an 8-bit immediate
  167 | _mm_castps_si128( _mm_insert_ps( _mm_castsi128_ps( v1 ), \
      | ^~~~~~~~~~~~~
./simd-utils/simd-128.h:183:12: note: in expansion of macro ‘mm128_xim_32’
  183 | { return mm128_xim_32( v, v, m ); }
      | ^~~~~~~~~~`
Make and make -j 8 both give the same error:
Due to failure to build the package from the path you provided.
I used the libraries here: https://packages.msys2.org/package/

Your packages provided I only successfully built openssl.
When I build the package gmp and curl both get an error.
Error for curl: 
make 
```
checking curl version... 7.80.0
configure: error: select TLS backend(s) or disable TLS with --without-ssl.

Select from these:

  --with-amissl
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-mesalink
  --with-nss
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl
```
Error for gmp: ```checking for build system executable suffix... configure: error: Cannot determine executable suffix```

**Comment by michal-zurkowski** [comment]
1. You are not using any CXXFLAGS.
2. Everything builds perfectly on Ubuntu no problem.
3. It was not tested using msys2 on Windows to compile.
4. I can see you did not follow the instructions on the repo... https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/main/INSTALL_WINDOWS

**Comment by vanthoi** [comment]
> 1. You are not using any CXXFLAGS.
> 2. Everything builds perfectly on Ubuntu no problem, tested different versions, Server, and Desktop on 18.04, 20.04, 21.04
> 3. It was not tested using msys2 on Windows to compile.
> 4. I can see you did not follow the instructions on the repo... https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/main/INSTALL_WINDOWS

Thank you for pointing out where my fever is missing. After adding the following command I built successfully.

```CFLAGS="-O3 -march=native -mtune=native ${DCFLAGS}" \
CXXFLAGS="$CFLAGS -std=c++2a -fconcepts -Wno-ignored-attributes" \
./configure --with-crypto --with-curl --host=x86_64-w64-mingw32```

For libraries like curl and gmp I am not able to build with Ubuntu 20.04 on WSL2 version. So I installed the above libraries via the address I provided above. You can also reference it for your project without building and rebuilding the library.

**Comment by michal-zurkowski** [comment]
So not Ubuntu but WSL.
Thanks for the info.
