### ISSUE TITLE
Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Mandeepsheoran** [WyvernTKC/cpuminer-gr-avx2#72]
I am using Minikube VM for kubernetes, while pulling any docker image in VM its throwing below error:

Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority

I copied all certificates from /etc/docker folder to /etc/docker/certs.d, as suggested by some user and restarted the docker as well, but still getting same issue.

**Comment by michal-zurkowski** [comment]
I'm sorry, that looks more like a Kubernetes problem, not the miner itself. I'm sure you will find more help googling it.
