### ISSUE TITLE
Miner asking for root permissions on Linux

### ISSUE THREAD

**Issue by Nixola** [WyvernTKC/cpuminer-gr-avx2#73]
Hi, I recently started mining using this software and I noticed some warning about hugepages and MSR, and running as root being required to set those up. I'm not quite comfortable doing that, if I have to be entirely honest, and I'd like to know what exactly needs to be set up so that I may do it manually instead of having the miner do so.

**Comment by michal-zurkowski** [comment]
Then you will have to set up Huge pages manually on your system, Google it.
MSR is a modification on CPU registers to disable hardware prefetch. Search for MSR tools and how to disable prefetch if you want to do it manually. Also, google it for your specific CPU which registers should be changed.
After that, you can run miner as a normal user. It will still try to enable MSR for you but it should not matter as you set it manually and Large Pages will also work just fine.

**Comment by JosefRypacek** [comment]
It would be fine if miner can suggest recommended commands / values for huge pages and MSR. As miner must know the values, it should be easy to implement.

There are some examples of settings, but not every user will know what exactly to use. It seems that my CPU needs 1 huge page for each thread.
https://xmrig.com/docs/miner/hugepages
https://xmrig.com/docs/miner/randomx-optimization-guide/msr
