### ISSUE TITLE
how can i test the configs  speed on cpu?

### ISSUE THREAD

**Issue by jay52121** [WyvernTKC/cpuminer-gr-avx2#75]
I gat 3 configs on my cpu(5800X)，how can i test which one is best?
Full test need too much times.

**Comment by michal-zurkowski** [comment]
You can swap those configs and run benchmark in the miner.

**Comment by jay52121** [comment]
tks! but how can i run benchmark ?  there is no docs for it...

**Comment by Chipcraft** [comment]
Either by adding "--benchmark" to the command line parameters, or by adding a boolean to the JSON config-file:

"benchmark": true,

**Comment by michal-zurkowski** [comment]
In the readme you have all available flags and how to use them in config.
