### ISSUE TITLE
[Feature Request] Use Less Than Max Cores

### ISSUE THREAD

**Issue by Meatball13** [WyvernTKC/cpuminer-gr-avx2#80]
Would like to request a feature that allows you to either pick a total number or percentage of available cores that you mine with.

**Comment by michal-zurkowski** [comment]
It is already there. Reading readme.txt or help of the miner next time....
flag is `threads`

**Comment by Meatball13** [comment]
Ah, my bad.  Sorry, searched on cores and didn't find it.
