### ISSUE TITLE
Windows server 2016 and Ryzen 5800x

### ISSUE THREAD

**Issue by tomganleylee** [WyvernTKC/cpuminer-gr-avx2#87]
So i am having some issues trying to get one of my machines minning.

System:
OS: Windows server 2016
CPU: 5800x

I keep getting this error:

Prepared for Windows - NTver: 0x601
CPU: AMD Ryzen 7 5800X 8-Core Processor
SW built on Nov 10 2021 with GCC 10.0.0
CPU features:  AVX2    AES
SW features:   AVX2   VAES SHA
Algo features: AVX2   VAES
The SW build requires a CPU with VAES!

anyon have any idea whats wrong, i have 5800x and 5900x working fine on other machines

Thanks in advance

**Comment by michal-zurkowski** [comment]
Looks like you have some features disabled in the bios for this CPU or something.
It should be able to do VAES and SHA but as you can see, it is disabled.
open cpuminer.bat and change line 11 to this `set INST_OVERRIDE=avx2`
