### ISSUE TITLE
Failed to start WinRing0 driver

### ISSUE THREAD

**Issue by SparlyDavidson** [WyvernTKC/cpuminer-gr-avx2#89]
I just installed the Raptoreum cpu miner and I get this error that I am unable to troubleshoot.

1. I have setup the binaries with admin rights
2. I have run the cpuminer.bat with admin rights

![Screenshot 2021-11-14 205603](https://user-images.githubusercontent.com/94338592/141720173-1a38b162-4258-4285-975b-6eb863fba622.png)

Would like some assistance.  Thank you!

**Comment by michal-zurkowski** [comment]
183 means something else is using same thing.

Try closing all monitoring software like HWInfo, afterburner, some watercooling monitoring stuff etc.

**Comment by SparlyDavidson** [comment]
> 183 means something else is using same thing.
> 
> Try closing all monitoring software like HWInfo, afterburner, some watercooling monitoring stuff etc.

I stopped NiceHash to see if it was the issue and it was.  I ran the cpuminer.bat first and had no errors.  I started NiceHash afterwards and no errors there, so I assume as long as I start the cpu miner 1st, I will be fine.
