### ISSUE TITLE
[Q] Are the presets still valid?

### ISSUE THREAD

**Issue by RainbowMiner** [WyvernTKC/cpuminer-gr-avx2#91]
Like the title says:
are the presets in folder https://github.com/WyvernTKC/cpuminer-gr-avx2/tree/main/bin/tune_presets_1.1.7 still valid for the current release of the miner?

**Comment by michal-zurkowski** [comment]
No, they are not valid anymore.
Doing tuning on your own hardware is highly recommended.
Unless you have exact same CPU with the same OC and RAM configuration, using someone else's config can lead to lower performance.
