### ISSUE TITLE
Version 1.2.4.1 gives "Could not load 'tune_config' file error"

### ISSUE THREAD

**Issue by AdV3nt5187** [WyvernTKC/cpuminer-gr-avx2#92]
Hi,

I get the error "Could not load 'tune_config' file error" with version 1.2.4.1 where as testing with8 the config file and running it on 1.2.0 does not give the error, the only issue that to me makes sense is that I am running into a problem with the section of the batch file below.

:RunBinary
set CPU_INST="%1"
echo Detected %1 compatible binary with %2 architecture
echo Change line 11 if CPU was not detected properly.
call :StartMiner

:StartMiner
echo If file is "missing" please check if Windows Defender or AV did not block/remove it from binaries folder.
binaries\cpuminer-!CPU_INST!.exe --config=config.json
timeout 5 > NUL
goto StartMiner

This section varies compared to 1.2.0, I am running windows 11 and have disabled AV etc.

**Comment by michal-zurkowski** [comment]
If you did not copy over tune_config from 1.2.0 folder to 1.2.4.1 folder, then of course it is missing and you will have to tune again.
This file is created by the miner after tuning so it is not there by default so miner tunes on new system.

**Comment by AdV3nt5187** [comment]
Wow such a simple thing, quite stupid of me, thank you for the response, first time using the miner so I was unaware of this.
