### ISSUE TITLE
cpuminer stuck after block acceptance

### ISSUE THREAD

**Issue by SodoTeo** [WyvernTKC/cpuminer-gr-avx2#93]
Hello guys,

I just got into mining with raptoreum. I started to mine with my laptop (just to taste the experience), after that I decided to mine on my workstation. After the tuning was done I saw that the miner connected to the stratum but wont take any shares from blocks to mine (like I saw with my laptop). 

Instead it stays stuck at this phase:  https://imgur.com/S0Tsnz7

What i tried :
- Restart pc
- Run from cmd (as admin)
- Created new transaction in the wallet just for the workstation
- Run with tune config file
- Run without tune
- Run via cmd with --verify parameter
- Delete and extract again the file (I keeped the json and tune files from the previous folder)

Any thoughts on what can get wrong?

Thank you in advance any help will be appreciated.

**Comment by michal-zurkowski** [comment]
Your run it on Windows, this is the first mistake xD
Ok, when you start it and it "stops", go to task manager and see if it is suspended. It is possible windows stopped it. If it is suspended, go to Resource Monitor and find the miner process, then right click and "Resume", it should start doing its job.

**Comment by SodoTeo** [comment]
Thank you for your comment, I am in transit right now so unfortunately I have remote access just to windows ( I have also garuda and ubuntu but no remote access )

I don't know how i didn't thought that windows might do something this stupid xD but with so simple solution.
And yeah now its mining just fine thanks again.
