### ISSUE TITLE
Hive os error when i switched to new version of miner

### ISSUE THREAD

**Issue by Maythecoffee** [WyvernTKC/cpuminer-gr-avx2#95]
Sorry, i copied this from my screenshot, so some mistake definitely are here)
"Running cpuminer-opt-gr optimised for avx2-sha hive/miners/cpuminer-opt/h-run.sh : line 48 ./vpuminer-avx2-sha: no suchfile or directory 

cpuminer-op exited (exitcode=0), waiting for cooldown a bit"

so this message appeared when i switched from 1.2.2 to 1.2.4.1 
And same message appeared when i applied older 1.2.2 version to new rig with 1.2.4.1 

How to fix it?

P.S after i returned to 1.2.2 all rigs again started full tune process/

**Comment by Maythecoffee** [comment]
![Uploading 7F94C2E6-CB35-43C9-9D1A-FD9BC9DFC240.jpeg…]()

**Comment by michal-zurkowski** [comment]
Please make sure you update your HiveOS. First few Hive releases after miner release are broken.
Miner should work with no problem with the latest HiveOS version.

**Comment by Maythecoffee** [comment]
The issue has been appeared on 3 my current rigs, right, but the same issue I see on my new rig which I set up with 1.2.4.1 and then downgraded it to 1.2.2 (because of one flight sheet for all rigs), this least=rig is fully updated , but same issue appeared during switching of miner!

**Comment by michal-zurkowski** [comment]
Like i said, there is no avx2-sha in the binaries in the latest version.
If you have problems, contact HiveOs team as they are the ones adding is weirdly to the system without checks.
