### ISSUE TITLE
Zen cpu detector uses cpu model 24 for both zen and zen+

### ISSUE THREAD

**Issue by slowpeek** [WyvernTKC/cpuminer-gr-avx2#96]
https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/d2e391d29a0e9a42de2b85c25d51824b58554411/bin/cpuminer.sh#L45-L49

You probably took the for data from https://en.wikichip.org/wiki/amd/cpuid which incorrectly (?) lists model=24 for both zen and zen+

**Comment by michal-zurkowski** [comment]
Both use the same binaries so it is not a problem.
